source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Added Gems
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'
gem 'bson_ext'
gem 'bootstrap-sass', '~> 3.1.1.0'
gem 'bcrypt', '~> 3.1.5'
gem 'devise', '~> 3.2.4'

group :development, :test do
	gem 'rspec-rails', '~> 2.14.2'
	gem 'capybara', '~> 2.2.1'
	gem 'ZenTest', '~> 4.9.5'
	gem 'autotest-rails', '~> 4.2.1'
	gem 'tzinfo', '~> 1.1.0'
	gem 'tzinfo-data', '~> 1.2014.2'
 end

group :test do
	gem 'selenium-webdriver', '~> 2.41.0'
	gem 'database_cleaner', '~> 1.2.0'
end

group :development do
	gem 'better_errors', '~> 1.1.0'
	gem 'binding_of_caller', '~> 0.7.2'
end
